#!/usr/bin/env python3
"""Merger — generate Strudel songs from sampler-chopped audio.

The companion script to ../sampler/sampler.py. The sampler chops an MP3 /
WAV into one-shot slices and sorts them into bass/kick/melody/other
folders. The merger then walks those folders, builds a strudel.json that
indexes every slice by category, and writes complete .strudel files that
play patterns built from those samples.

Typical workflow:

    # 1. Run the sampler on some audio
    cd ../sampler
    python sampler.py mytrack.mp3 -o output

    # 2. Run the merger pointed at the sampler's output
    cd ../merger
    python merger.py -i ../sampler/output -n 8

    # 3. Serve the repo and open the player, or paste one of the
    #    generated files into strudel.cc — the samples load from the
    #    same folder as strudel.json (relative ./samples paths).

Generated files land in merger/output/ alongside a strudel.json that
lists every slice. Each song picks random samples from the categories
and slots them into one of several musical templates (lofi, boom-bap,
techno, ambient, breakbeat).

Usage examples:

    python merger.py                              # use defaults
    python merger.py -i ../sampler/output -n 12   # 12 songs, custom in
    python merger.py --seed 42                    # reproducible run
    python merger.py --templates lofi,techno      # only these styles
    python merger.py --base-url 'github:owner/repo/main/tools/merger/output/'
                                                  # use the GitHub
                                                  # sample-pack path
                                                  # instead of relative

Requires no dependencies — pure stdlib Python.
"""

from __future__ import annotations

import argparse
import json
import random
import re
import sys
from pathlib import Path
from typing import Callable


# ── Configuration ────────────────────────────────────────────────────────────

HERE = Path(__file__).parent

# Where the sampler dumps its output by default. The merger doesn't
# require this exact layout — any folder with kick/bass/melody/other
# subdirectories of wav files works.
DEFAULT_INPUT  = HERE.parent / "sampler" / "output"
DEFAULT_OUTPUT = HERE / "output"

# Mapping from "what Strudel calls the bank" → "what the sampler calls the
# folder". The shorter Strudel keys read better inside s("kick:0 ...").
CATEGORIES = {
    "kick":  "kick",
    "bass":  "bass",
    "mel":   "melody",
    "other": "other",
}

# Recognised audio file extensions when scanning the sampler output.
AUDIO_EXTS = {".wav", ".mp3", ".ogg", ".flac", ".aif", ".aiff"}


# ── Sample indexing ──────────────────────────────────────────────────────────

def index_samples(input_dir: Path) -> dict[str, list[str]]:
    """Walk the input dir's category subfolders and list every audio file.

    Returns a dict whose keys are the Strudel bank names (kick, bass, mel,
    other) and whose values are lists of paths relative to `input_dir`.
    Missing categories yield an empty list — the templates handle that.
    """
    result: dict[str, list[str]] = {}
    for strudel_key, folder_name in CATEGORIES.items():
        sub = input_dir / folder_name
        if not sub.is_dir():
            result[strudel_key] = []
            continue
        files = sorted(
            f"{folder_name}/{f.name}"
            for f in sub.iterdir()
            if f.is_file() and f.suffix.lower() in AUDIO_EXTS
        )
        result[strudel_key] = files
    return result


def build_strudel_json(index: dict[str, list[str]], base_url: str) -> dict:
    """Format the index as a strudel.json mapping.

    `_base` is the URL prefix every sample path is appended to. Default
    is "./" so the JSON works when served from the same folder it lives
    in. Pass `--base-url github:owner/repo/branch/path/` to publish.
    """
    out: dict = {"_base": base_url}
    for key, paths in index.items():
        if paths:
            out[key] = paths
    return out


# ── Template helpers ─────────────────────────────────────────────────────────

def pick(rng: random.Random, count: int, n: int) -> list[int]:
    """Return `n` sample indices in [0, count). Falls back to 0s when the
    category is empty so the generated code stays valid but silent."""
    if count <= 0:
        return [0] * n
    return [rng.randrange(count) for _ in range(n)]


def has_layer(index: dict[str, list[str]], key: str) -> bool:
    return len(index.get(key, [])) > 0


def header(title: str, template_name: str, bpm: float, theory: str,
           index: dict[str, list[str]]) -> str:
    counts = ", ".join(f"{k}: {len(v)}" for k, v in index.items())
    return (
        f"// ══════════════════════════════════════════════════════════════\n"
        f"// \"{title}\"\n"
        f"// {template_name}\n"
        f"//\n"
        f"// Tempo:  {bpm:g} BPM\n"
        f"// Theory: {theory}\n"
        f"// Pool:   {counts}\n"
        f"//\n"
        f"// Generated by merger.py from sampler output.\n"
        f"// ══════════════════════════════════════════════════════════════\n"
    )


# ── Templates ────────────────────────────────────────────────────────────────
#
# Each template returns (title, code). The code references samples via
# `s("kick:0 ...")` syntax which looks up the kick bank in strudel.json.

def template_lofi(rng: random.Random, index: dict[str, list[str]]) -> tuple[str, str]:
    nk, nb, nm, no = (len(index[k]) for k in ("kick", "bass", "mel", "other"))
    k = pick(rng, nk, 2)
    b = pick(rng, nb, 2)
    m = pick(rng, nm, 4)
    o = pick(rng, no, 2)

    title = "Lofi Loop"
    cpm   = 17.5      # ~70 BPM
    theory = "kick on 1+3, snare-role on 2+4, sparse melody with delay"

    parts = []
    if nk: parts.append(f'  s("kick:{k[0]} ~ ~ ~ kick:{k[1]} ~ ~ ~").gain(0.85).lpf(2500)')
    if no: parts.append(f'  s("~ ~ other:{o[0]} ~ ~ ~ other:{o[1]} ~").gain(0.6).hpf(200).room(0.18)')
    if nb: parts.append(f'  s("bass:{b[0]} ~ ~ ~ bass:{b[1]} ~ ~ ~").gain(0.7).lpf(500)')
    if nm: parts.append(
        f'  s("mel:{m[0]} ~ mel:{m[1]} ~ mel:{m[2]} ~ ~ mel:{m[3]}")\n'
        f'    .gain(0.5).delay(0.3).delaytime(0.375).delayfeedback(0.25)\n'
        f'    .room(0.32)'
    )

    code = (
        header(title, "Lofi loop — slow, mellow, delayed", 70, theory, index) +
        "\nsamples('./strudel.json')\n\n"
        f"setcpm({cpm})\n\n"
        "stack(\n" + ",\n".join(parts) + "\n)\n"
    )
    return title, code


def template_boombap(rng: random.Random, index: dict[str, list[str]]) -> tuple[str, str]:
    nk, nb, nm, no = (len(index[k]) for k in ("kick", "bass", "mel", "other"))
    k = pick(rng, nk, 3)
    b = pick(rng, nb, 4)
    m = pick(rng, nm, 4)
    o = pick(rng, no, 3)

    title = "Boom Bap Chop"
    cpm   = 22
    theory = "kick on 1 + &-of-3, snare-role on 2+4, walking bass, vinyl crackle"

    parts = []
    if nk: parts.append(f'  s("kick:{k[0]} ~ ~ ~ ~ kick:{k[1]} ~ kick:{k[2]}").gain(0.9).lpf(220)')
    if no: parts.append(f'  s("~ ~ other:{o[0]} ~ ~ ~ other:{o[1]} ~").gain(0.7).hpf(220).room(0.16)')
    if no: parts.append(f'  s("other:{o[2]}*16").gain(0.05).hpf(7000).degradeBy(0.55)  // vinyl crackle')
    if nb: parts.append(f'  s("bass:{b[0]} ~ bass:{b[1]} ~ bass:{b[2]} ~ bass:{b[3]} ~").gain(0.75).lpf(420)')
    if nm: parts.append(
        f'  s("mel:{m[0]} ~ ~ mel:{m[1]} ~ mel:{m[2]} ~ mel:{m[3]}")\n'
        f'    .gain(0.55).lpf(3200)\n'
        f'    .delay(0.32).delaytime(0.375).delayfeedback(0.25)'
    )

    code = (
        header(title, "Boom-bap — 88 BPM hip-hop chop", 88, theory, index) +
        "\nsamples('./strudel.json')\n\n"
        f"setcpm({cpm})\n\n"
        "stack(\n" + ",\n".join(parts) + "\n)\n"
    )
    return title, code


def template_techno(rng: random.Random, index: dict[str, list[str]]) -> tuple[str, str]:
    nk, nb, nm, no = (len(index[k]) for k in ("kick", "bass", "mel", "other"))
    k = pick(rng, nk, 1)
    b = pick(rng, nb, 1)
    m = pick(rng, nm, 2)
    o = pick(rng, no, 3)

    title = "Techno Pump"
    cpm   = 32.5
    theory = "four-on-the-floor kick, sub bass, off-beat hat, sparse melody"

    parts = []
    if nk: parts.append(f'  s("kick:{k[0]}*4").gain(0.95).lpf(170).shape(0.18)')
    if no: parts.append(f'  s("~ other:{o[0]} ~ other:{o[1]}").gain(0.5).hpf(3500)  // off-beat hat / perc')
    if no: parts.append(f'  s("~ ~ other:{o[2]} ~").gain(0.55).hpf(220).room(0.2)   // clap on 2/4')
    if nb: parts.append(f'  s("bass:{b[0]}*8").gain(0.7).lpf(420).struct("x ~ x x ~ x ~ x")')
    if nm: parts.append(
        f'  s("mel:{m[0]} ~ ~ ~ ~ ~ mel:{m[1]} ~").gain(0.42)\n'
        f'    .lpf(2400).delay(0.3).delaytime(0.333).delayfeedback(0.35)\n'
        f'    .room(0.4).slow(2)'
    )

    code = (
        header(title, "Techno — 130 BPM four-on-the-floor", 130, theory, index) +
        "\nsamples('./strudel.json')\n\n"
        f"setcpm({cpm})\n\n"
        "stack(\n" + ",\n".join(parts) + "\n)\n"
    )
    return title, code


def template_ambient(rng: random.Random, index: dict[str, list[str]]) -> tuple[str, str]:
    nk, nb, nm, no = (len(index[k]) for k in ("kick", "bass", "mel", "other"))
    k = pick(rng, nk, 1)
    b = pick(rng, nb, 2)
    m = pick(rng, nm, 5)
    o = pick(rng, no, 3)

    title = "Ambient Drift"
    cpm   = 12
    theory = "no beat, drone bass, melody chops with long reverb tails"

    parts = []
    # No regular kick — use one occasionally as a heartbeat
    if nk: parts.append(f'  s("kick:{k[0]} ~ ~ ~ ~ ~ ~ ~").gain(0.45).lpf(140).slow(2)')
    if nb: parts.append(
        f'  s("bass:{b[0]} ~ ~ ~ ~ ~ ~ ~  ~ ~ ~ ~ bass:{b[1]} ~ ~ ~")\n'
        f'    .gain(0.55).lpf(380).attack(0.5).release(2)\n'
        f'    .room(0.45).size(0.75)'
    )
    if nm: parts.append(
        f'  s("mel:{m[0]} ~ ~ mel:{m[1]} ~ ~ mel:{m[2]} ~  ~ mel:{m[3]} ~ ~ ~ ~ mel:{m[4]} ~")\n'
        f'    .gain(0.4).delay(0.5).delaytime(0.5).delayfeedback(0.5)\n'
        f'    .room(0.7).size(0.9).pan(rand).degradeBy(0.35)'
    )
    if no: parts.append(
        f'  s("other:{o[0]} ~ ~ ~  ~ other:{o[1]} ~ ~  ~ ~ ~ other:{o[2]}  ~ ~ ~ ~")\n'
        f'    .gain(0.3).hpf(1500).room(0.6).pan(rand).degradeBy(0.5)'
    )

    code = (
        header(title, "Ambient — slow, sparse, very wet", 50, theory, index) +
        "\nsamples('./strudel.json')\n\n"
        f"setcpm({cpm})\n\n"
        "stack(\n" + ",\n".join(parts) + "\n)\n"
    )
    return title, code


def template_breakbeat(rng: random.Random, index: dict[str, list[str]]) -> tuple[str, str]:
    nk, nb, nm, no = (len(index[k]) for k in ("kick", "bass", "mel", "other"))
    k = pick(rng, nk, 4)
    b = pick(rng, nb, 2)
    m = pick(rng, nm, 3)
    o = pick(rng, no, 6)

    title = "Breakbeat Chop"
    cpm   = 42
    theory = "chopped break pattern, sub bass, melodic chops, atmospheric pads"

    parts = []
    # Chopped break — uses a mix of kick + other to imitate a breakbeat
    if nk and no:
        parts.append(
            f'  s("kick:{k[0]} other:{o[0]} kick:{k[1]} other:{o[1]}  '
            f'kick:{k[2]} kick:{k[3]} other:{o[2]} other:{o[3]}")\n'
            f'    .gain(0.78).lpf(4500)'
        )
    if no: parts.append(f'  s("other:{o[4]}*16").gain(0.25).hpf(5500).pan("0.4 0.6")')
    if nb: parts.append(f'  s("bass:{b[0]} ~ ~ ~ bass:{b[1]} ~ ~ ~").gain(0.7).lpf(380)')
    if nm: parts.append(
        f'  s("mel:{m[0]} ~ mel:{m[1]} ~ ~ mel:{m[2]} ~ ~")\n'
        f'    .gain(0.42).lpf(2800)\n'
        f'    .delay(0.4).delaytime(0.333).delayfeedback(0.32).room(0.45).slow(2)'
    )
    if no: parts.append(f'  s("~ ~ ~ ~ ~ ~ ~ other:{o[5]}").gain(0.4).hpf(2000).room(0.4)')

    code = (
        header(title, "Breakbeat — 168 BPM chopped jungle/DnB feel", 168, theory, index) +
        "\nsamples('./strudel.json')\n\n"
        f"setcpm({cpm})\n\n"
        "stack(\n" + ",\n".join(parts) + "\n)\n"
    )
    return title, code


TEMPLATES: dict[str, Callable[[random.Random, dict[str, list[str]]], tuple[str, str]]] = {
    "lofi":      template_lofi,
    "boombap":   template_boombap,
    "techno":    template_techno,
    "ambient":   template_ambient,
    "breakbeat": template_breakbeat,
}


# ── Output writing ───────────────────────────────────────────────────────────

def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("-i", "--input",  type=Path, default=DEFAULT_INPUT,
                        help=f"Sampler output folder (default: {DEFAULT_INPUT})")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT,
                        help=f"Where to write strudel.json + songs (default: {DEFAULT_OUTPUT})")
    parser.add_argument("-n", "--count",  type=int, default=8,
                        help="How many songs to generate (default: 8)")
    parser.add_argument("--seed", type=int, default=None,
                        help="Random seed for reproducible runs")
    parser.add_argument("--templates", default=",".join(TEMPLATES.keys()),
                        help=f"Comma-separated template names. Available: {','.join(TEMPLATES.keys())}")
    parser.add_argument("--base-url", default="./",
                        help="strudel.json _base URL. Default './' (relative). "
                             "Use 'github:owner/repo/branch/path/' to publish.")
    args = parser.parse_args()

    if not args.input.is_dir():
        sys.exit(f"input folder not found: {args.input}\n"
                 f"Run ../sampler/sampler.py first to produce some samples.")

    # Validate templates
    chosen = [t.strip() for t in args.templates.split(",") if t.strip()]
    bad = [t for t in chosen if t not in TEMPLATES]
    if bad:
        sys.exit(f"unknown template(s): {bad}. Valid: {list(TEMPLATES)}")

    # Build the sample index
    index = index_samples(args.input)
    total = sum(len(v) for v in index.values())
    if total == 0:
        sys.exit(f"no audio files found under {args.input}/kick,bass,melody,other/")

    print(f"Indexed {total} samples from {args.input}:")
    for k, v in index.items():
        print(f"  {k:6}: {len(v):3d}")

    # Write strudel.json
    args.output.mkdir(parents=True, exist_ok=True)
    strudel_json = build_strudel_json(index, args.base_url)
    json_path = args.output / "strudel.json"
    json_path.write_text(json.dumps(strudel_json, indent=2))
    print(f"\nWrote {json_path}")

    # Generate songs
    rng = random.Random(args.seed)
    print(f"\nGenerating {args.count} songs from templates {chosen}:")
    for i in range(1, args.count + 1):
        template_name = chosen[(i - 1) % len(chosen)]
        title, code = TEMPLATES[template_name](rng, index)
        # Run-uniquify the title with the index
        filename = f"song-{i:02d}-{template_name}-{slug(title)}.strudel"
        out_path = args.output / filename
        out_path.write_text(code)
        print(f"  → {filename}")

    print(f"\nDone. Open one of the .strudel files via the player, or serve "
          f"{args.output} and load directly in strudel.cc.")


if __name__ == "__main__":
    main()
