const PLAYLISTS = [
  {
    id: 'lofi',
    label: 'LOFI',
    theme: 'lofi',
    path: '../lofi/',
    mode: 'player',
    files: [
      'song-01-3am-rain.strudel',
      'song-02-blue-smoke.strudel',
      'song-03-sunday-corner.strudel',
      'song-04-midnight-walk.strudel',
      'song-05-cafe-creme.strudel',
      'song-06-harbour-fog.strudel',
      'song-07-golden-afternoon.strudel',
      'song-08-neon-puddles.strudel',
      'song-09-midnight-thoughts.strudel',
      'song-10-lazy-afternoon.strudel',
      'song-11-rainy-window.strudel',
      'song-12-morning-stroll.strudel',
      'song-13-evening-reflections.strudel',
      'song-14-sunrise-hope.strudel',
      'song-15-night-whispers.strudel',
      'song-16-dark-dreams.strudel',
      'song-17-quiet-streets.strudel',
      'song-18-summer-breeze.strudel',
      'song-19-velvet-night.strudel',
      'song-20-coffee-shop-afternoon.strudel',
      'song-21-winter-silence.strudel',
      'song-22-ocean-drift.strudel',
      'song-23-urban-solitude.strudel',
      'song-24-starlight-garden.strudel',
      'song-25-autumn-leaves.strudel',
      'song-26-foggy-morning.strudel',
      'song-27-deep-blue-hour.strudel',
      'song-28-soft-static.strudel',
      'song-29-half-dream.strudel',
      'song-30-porch-rain.strudel',
    ],
  },
  {
    id: 'rim',
    label: 'RIM',
    theme: 'rim',
    path: '../rim/',
    mode: 'player',
    files: [
      'song-01-dusty-trail.strudel',
      'song-02-campfire-lullaby.strudel',
      'song-03-prairie-wind.strudel',
      'song-04-old-tin-roof.strudel',
      'song-05-sagebrush-sunset.strudel',
      'song-06-lonesome-canyon.strudel',
      'song-07-creek-crossing.strudel',
      'song-08-red-mesa-morning.strudel',
      'song-09-old-porch-swing.strudel',
      'song-10-desert-stars.strudel',
      'song-11-sunset-mesa.strudel',
      'song-12-whispering-pines.strudel',
      'song-13-slow-river.strudel',
      'song-14-moon-over-canyon.strudel',
      'song-15-last-light-ranch.strudel',
    ],
  },
  {
    id: 'acid',
    label: 'ACID',
    theme: 'acid',
    path: '../acid/',
    mode: 'player',
    files: [
      'acid-01-storm-warning.strudel',
      'acid-02-trance-ascension.strudel',
      'acid-03-chrome-cathedral.strudel',
      'acid-04-neural-dissolve.strudel',
      'acid-05-rave-protocol.strudel',
    ],
  },
  {
    id: 'skola',
    label: 'SKOLA',
    theme: 'skola',
    path: '../Skola/',
    mode: 'code',
    files: [
      'lesson-01-rhythm-basics.strudel',
      'lesson-02-mini-notation.strudel',
      'lesson-03-notes-and-pitch.strudel',
      'lesson-04-scales-and-melody.strudel',
      'lesson-05-chords-and-harmony.strudel',
      'lesson-06-synths-and-sound-design.strudel',
      'lesson-07-effects.strudel',
      'lesson-08-advanced-rhythm.strudel',
      'lesson-09-structure-and-arrangement.strudel',
      'lesson-10-full-track.strudel',
      'cheat-01-rhythm-and-patterns.strudel',
      'cheat-02-pitch-and-harmony.strudel',
      'cheat-03-sound-and-effects.strudel',
      'cheat-04-advanced-modifiers.strudel',
      'cheat-05-advanced-effects.strudel',
      'cheat-06-effects-library.strudel',
      'example.strudel',
    ],
  },
  {
    id: 'prog',
    label: 'PROG',
    theme: 'prog',
    path: '../prog/',
    mode: 'player',
    files: [
      'song-01-deep-focus.strudel',
      'song-02-stack-overflow.strudel',
      'song-03-git-commit.strudel',
      'song-04-midnight-compile.strudel',
      'song-05-lambda-calculus.strudel',
      'song-06-terminal-green.strudel',
      'song-07-async-await.strudel',
      'song-08-loop-invariant.strudel',
      'song-09-memory-leak.strudel',
      'song-10-zero-day.strudel',
      'song-11-idle-process.strudel',
      'song-12-dark-mode.strudel',
      'song-13-slow-build.strudel',
      'song-14-runtime-reflections.strudel',
      'song-15-quiet-daemon.strudel',
    ],
  },
  {
    id: 'techno',
    label: 'TECHNO',
    theme: 'techno',
    path: '../TehnoSkola/',
    mode: 'code',
    files: [
      'techno-01-detroit.strudel',
      'techno-02-berlin-minimal.strudel',
      'techno-03-acid-techno.strudel',
      'techno-04-dub-techno.strudel',
      'techno-05-industrial-techno.strudel',
      'techno-06-hard-techno.strudel',
      'techno-07-hypnotic-dark.strudel',
      'techno-08-melodic-techno.strudel',
      'techno-09-trance.strudel',
      'techno-10-gabber.strudel',
    ],
  },
  {
    id: 'yt',
    label: 'YT SFX',
    theme: 'yt',
    path: '../yt/',
    mode: 'player',
    files: [
      'sfx-01-swoosh.strudel',
      'sfx-02-happy-zoom.strudel',
      'sfx-03-success-ding.strudel',
      'sfx-04-soft-pop.strudel',
      'sfx-05-typewriter.strudel',
      'sfx-06-notification-chime.strudel',
      'sfx-07-paper-flip.strudel',
      'sfx-08-button-click.strudel',
      'sfx-09-tape-rewind.strudel',
      'sfx-10-record-scratch.strudel',
      'sfx-11-lightbulb-idea.strudel',
      'sfx-12-error-beep.strudel',
      'sfx-13-drumroll-reveal.strudel',
      'sfx-14-coin-drop.strudel',
      'sfx-15-soft-thump.strudel',
      'sfx-16-magic-sparkle.strudel',
      'sfx-17-clock-tick.strudel',
      'sfx-18-transition-whoosh.strudel',
      'sfx-19-correct-answer.strudel',
      'sfx-20-wrong-buzzer.strudel',
    ],
  },
  {
    id: 'game',
    label: 'GAME SFX',
    theme: 'game',
    path: '../game/',
    mode: 'player',
    files: [
      'sfx-01-coin-pickup.strudel',
      'sfx-02-jump.strudel',
      'sfx-03-power-up.strudel',
      'sfx-04-game-over.strudel',
      'sfx-05-level-up.strudel',
      'sfx-06-laser-shot.strudel',
      'sfx-07-explosion.strudel',
      'sfx-08-damage-hit.strudel',
      'sfx-09-menu-select.strudel',
      'sfx-10-arcade-start.strudel',
      'sfx-11-boss-warning.strudel',
      'sfx-12-retro-fanfare.strudel',
      'sfx-13-potion-drink.strudel',
      'sfx-14-sword-swing.strudel',
      'sfx-15-footsteps.strudel',
      'sfx-16-door-open.strudel',
      'sfx-17-checkpoint.strudel',
      'sfx-18-teleport.strudel',
      'sfx-19-silly-fail.strudel',
      'sfx-20-victory.strudel',
    ],
  },
  {
    id: 'jazz',
    label: 'JAZZ',
    theme: 'jazz',
    path: '../jazz-piano/',
    mode: 'player',
    files: [
      'jazz-01-midnight-confessions.strudel',
      'jazz-02-coltrane-steps.strudel',
      'jazz-03-modal-sunrise.strudel',
      'jazz-04-autumn-cycle.strudel',
      'jazz-05-lydian-dreams.strudel',
      'jazz-06-phrygian-twilight.strudel',
      'jazz-07-bossa-slow.strudel',
      'jazz-08-waltz-for-vera.strudel',
      'jazz-09-tritone-romance.strudel',
      'jazz-10-quartal-voyage.strudel',
      'jazz-11-bebop-lullaby.strudel',
      'jazz-12-diminished-rain.strudel',
      'jazz-13-modal-interchange.strudel',
      'jazz-14-stride-pastoral.strudel',
      'jazz-15-half-step-descent.strudel',
      'jazz-16-altered-dominant.strudel',
      'jazz-17-drop-2-voicings.strudel',
      'jazz-18-pedal-point.strudel',
      'jazz-19-seven-four-ballad.strudel',
      'jazz-20-so-what-shifts.strudel',
    ],
  },
  {
    id: 'study',
    label: 'STUDY',
    theme: 'study',
    path: '../study/',
    mode: 'player',
    files: [
      'study-01-focus-drone.strudel',
      'study-02-euclid-meditation.strudel',
      'study-03-phase-shift.strudel',
      'study-04-rain-piano.strudel',
      'study-05-canon-fifth.strudel',
      'study-06-markov-walk.strudel',
      'study-07-modal-vamp.strudel',
      'study-08-polymeter-7-5.strudel',
      'study-09-swing-shuffle.strudel',
      'study-10-chunk-variations.strudel',
      'study-11-iter-rotation.strudel',
      'study-12-struct-skeleton.strudel',
      'study-13-mask-silence.strudel',
      'study-14-arp-cascade.strudel',
      'study-15-amiga-tracker.strudel',
      'study-16-vcsl-strings.strudel',
      'study-17-mridangam-misra.strudel',
      'study-18-tr808-study.strudel',
      'study-19-clean-break-chop.strudel',
      'study-20-striate-textures.strudel',
      'study-21-harmonic-minor.strudel',
      'study-22-pentatonic-spirals.strudel',
      'study-23-counterpoint.strudel',
      'study-24-drone-overtones.strudel',
      'study-25-bell-jux.strudel',
      'study-26-ribbon-cycle.strudel',
      'study-27-squeeze-fill.strudel',
      'study-28-ply-pulses.strudel',
      'study-29-chop-amen.strudel',
      'study-30-almost-never.strudel',
    ],
  },
  {
    id: 'genres',
    label: 'GENRES',
    theme: 'genres',
    path: '../genres/',
    mode: 'player',
    files: [
      '01-boom-bap.strudel',
      '02-drill.strudel',
      '03-trap.strudel',
      '04-reggaeton.strudel',
      '05-dub.strudel',
      '06-ska.strudel',
      '07-tech-house.strudel',
      '08-acid-house.strudel',
      '09-uk-garage.strudel',
      '10-drum-and-bass.strudel',
      '11-jungle.strudel',
      '12-liquid-dnb.strudel',
      '13-footwork.strudel',
      '14-trip-hop.strudel',
      '15-synthwave.strudel',
      '16-vaporwave.strudel',
      '17-chillwave.strudel',
      '18-ambient.strudel',
      '19-dark-ambient.strudel',
      '20-italo-disco.strudel',
      '21-funk.strudel',
      '22-soul.strudel',
      '23-bebop.strudel',
      '24-cool-jazz.strudel',
      '25-fusion.strudel',
      '26-afrobeat.strudel',
      '27-cumbia.strudel',
      '28-salsa.strudel',
      '29-flamenco.strudel',
      '30-hindustani.strudel',
      '31-gamelan.strudel',
      '32-spaghetti-western.strudel',
      '33-surf-rock.strudel',
      '34-country.strudel',
      '35-bluegrass.strudel',
      '36-shoegaze.strudel',
      '37-math-rock.strudel',
      '38-post-rock.strudel',
      '39-doom-metal.strudel',
      '40-chiptune.strudel',
      '41-trance.strudel',
      '42-psytrance.strudel',
      '43-minimalism.strudel',
      '44-krautrock.strudel',
      '45-balearic.strudel',
      '46-happy-hardcore.strudel',
      '47-dancehall.strudel',
      '48-modern-rnb.strudel',
      '49-neo-soul.strudel',
      '50-drone.strudel',
    ],
  },
  {
    id: 'hardbass',
    label: 'HARD BASS',
    theme: 'hardbass',
    path: '../hard-bass/',
    mode: 'player',
    files: [
      '01-schranz-frankfurt.strudel',
      '02-industrial-hammer.strudel',
      '03-acid-303-hard.strudel',
      '04-hypnotic-loop.strudel',
      '05-hardgroove-roller.strudel',
      '06-broken-techno.strudel',
      '07-reverse-bass-hard.strudel',
      '08-gabber-fusion.strudel',
      '09-polyrhythm-bunker.strudel',
      '10-acid-roller.strudel',
      '11-funeral-procession.strudel',
      '12-distorted-vox.strudel',
      '13-modular-generative.strudel',
      '14-metallic-hammer.strudel',
      '15-sub-stab.strudel',
      '16-filter-sweep-epic.strudel',
      '17-detroit-hardgroove.strudel',
      '18-peak-time-banger.strudel',
      '19-tribal-hard.strudel',
      '20-closing-track.strudel',
    ],
  },
  {
    id: 'vocals',
    label: 'VOCALS',
    theme: 'vocals',
    path: '../vocals/',
    mode: 'player',
    files: [
      '01-vowel-choir.strudel',
      '02-alphabet-techno.strudel',
      '03-vocoder-house.strudel',
      '04-whisper-trip-hop.strudel',
      '05-vowel-bass-funk.strudel',
      '06-chopped-loop-dnb.strudel',
      '07-reverse-vocal-glitch.strudel',
      '08-call-response-jazz.strudel',
      '09-harmonic-vowels.strudel',
      '10-pitch-shift-rnb.strudel',
      '11-phone-vocal.strudel',
      '12-gregorian-chant.strudel',
      '13-shout-stab-hardcore.strudel',
      '14-rhythmic-numbers.strudel',
      '15-alphabet-melody-pop.strudel',
      '16-vocoder-bass-electro.strudel',
      '17-multi-voice-rap.strudel',
      '18-dub-vocal-echo.strudel',
      '19-vocal-pad-dorian.strudel',
      '20-stutter-vocal-glitch.strudel',
      '21-granular-striate-ambient.strudel',
      '22-autotune-style-pop.strudel',
      '23-call-response-gospel.strudel',
      '24-breathy-pad-rnb.strudel',
      '25-vocal-fx-techno.strudel',
      '26-chant-drone-mantra.strudel',
      '27-chord-vocoder.strudel',
      '28-trance-vocal-arp.strudel',
      '29-vocal-fragments-idm.strudel',
      '30-vowel-drone-finale.strudel',
    ],
  },
  {
    id: 'harmonic',
    label: 'HARMONIC',
    theme: 'harmonic',
    path: '../harmonic/',
    mode: 'player',
    files: [
      '01-opening-veil.strudel',
      '02-first-light.strudel',
      '03-threshold.strudel',
      '04-memory-stone.strudel',
      '05-slow-river.strudel',
      '06-quiet-garden.strudel',
      '07-crystal-bell.strudel',
      '08-inner-voice.strudel',
      '09-floating-glass.strudel',
      '10-long-shadow.strudel',
      '11-walking-through.strudel',
      '12-spiral-stairs.strudel',
      '13-two-voices.strudel',
      '14-echoing-hall.strudel',
      '15-slow-pulse.strudel',
      '16-beneath-the-surface.strudel',
      '17-birch-forest.strudel',
      '18-tide-going-out.strudel',
      '19-mosaic-floor.strudel',
      '20-open-window.strudel',
      '21-distant-bells.strudel',
      '22-snow-falling.strudel',
      '23-long-bow-drone.strudel',
      '24-garden-at-dusk.strudel',
      '25-cardinal-direction.strudel',
      '26-soft-rain.strudel',
      '27-old-hymn.strudel',
      '28-field-of-stars.strudel',
      '29-returning-home.strudel',
      '30-final-light.strudel',
    ],
  },
  {
    id: 'medeival',
    label: 'MEDEIVAL',
    theme: 'medeival',
    path: '../medeival/',
    mode: 'player',
    files: [
      '01-plainchant-opening.strudel',
      '02-stone-cathedral.strudel',
      '03-vespers-bell.strudel',
      '04-hurdy-gurdy.strudel',
      '05-lauda.strudel',
      '06-estampie.strudel',
      '07-sackbut-procession.strudel',
      '08-crusaders-march.strudel',
      '09-court-lute.strudel',
      '10-maidens-lament.strudel',
      '11-hymn-to-the-virgin.strudel',
      '12-black-death.strudel',
      '13-monks-procession.strudel',
      '14-throne-room.strudel',
      '15-gregorian-echo.strudel',
      '16-pilgrims-path.strudel',
      '17-tournament-fanfare.strudel',
      '18-tavern-round.strudel',
      '19-mystery-play.strudel',
      '20-final-mass.strudel',
    ],
  },
  {
    id: 'bluegrass',
    label: 'BLUEGRASS',
    theme: 'bluegrass',
    path: '../bluegrass/',
    mode: 'player',
    files: [
      '01-cabin-on-the-ridge.strudel',
      '02-foggy-hollow-breakdown.strudel',
      '03-wagon-wheel-waltz.strudel',
      '04-salt-creek-reel.strudel',
      '05-long-train-coming.strudel',
      '06-whiskey-before-breakfast.strudel',
      '07-coal-miners-lament.strudel',
      '08-bill-cheatham.strudel',
      '09-blackberry-blossom.strudel',
      '10-old-joe-clark.strudel',
      '11-high-lonesome.strudel',
      '12-sally-goodin.strudel',
      '13-dueling-strings.strudel',
      '14-sunday-porch.strudel',
      '15-last-train-home.strudel',
    ],
  },
  {
    id: 'idm',
    label: 'IDM',
    theme: 'idm',
    path: '../idm/',
    mode: 'player',
    files: [
      '01-glitch-pulse.strudel',
      '02-polymetric-drift.strudel',
      '03-granular-dust.strudel',
      '04-aphex-sleep.strudel',
      '05-autechre-lattice.strudel',
      '06-bitcrushed-memory.strudel',
      '07-probability-cloud.strudel',
      '08-tempo-modulation.strudel',
      '09-fractured-beats.strudel',
      '10-acid-resonance.strudel',
      '11-vector-algebra.strudel',
      '12-stutter-delay.strudel',
      '13-modular-patch.strudel',
      '14-reverse-cascade.strudel',
      '15-polyrhythm-engine.strudel',
      '16-crystal-ping.strudel',
      '17-microsound.strudel',
      '18-pitch-shifted-dream.strudel',
      '19-generative-bloom.strudel',
      '20-final-pattern.strudel',
    ],
  },
  {
    id: 'demos',
    label: 'DEMOS',
    theme: 'demos',
    path: '../pack-demos/',
    mode: 'player',
    files: [
      'algorave-dave-1-acid.strudel',
      'algorave-dave-2-techno.strudel',
      'amen-1-dnb.strudel',
      'amen-2-boom_bap.strudel',
      'amiga-1-chiptune.strudel',
      'amiga-2-idm.strudel',
      'audite-1-ambient.strudel',
      'audite-2-idm.strudel',
      'bratpeki-1-dnb.strudel',
      'bratpeki-2-trap.strudel',
      'bubo-samples-1-techno.strudel',
      'bubo-samples-2-ambient.strudel',
      'capoeira-1-ethnic.strudel',
      'capoeira-2-ambient.strudel',
      'cavlp-1-idm.strudel',
      'cavlp-2-techno.strudel',
      'clean-breaks-1-dnb.strudel',
      'clean-breaks-2-boom_bap.strudel',
      'crate-1-boom_bap.strudel',
      'crate-2-trap.strudel',
      'danigb-1-pop.strudel',
      'danigb-2-techno.strudel',
      'departure-1-ambient.strudel',
      'departure-2-idm.strudel',
      'dirt-1-boom_bap.strudel',
      'dirt-2-techno.strudel',
      'dough-1-lofi.strudel',
      'dough-2-house.strudel',
      'elomorelo-1-pop.strudel',
      'elomorelo-2-house.strudel',
      'emptyflash-1-house.strudel',
      'emptyflash-2-trap.strudel',
      'emrex-1-techno.strudel',
      'emrex-2-dnb.strudel',
      'estuary-1-ambient.strudel',
      'estuary-2-lofi.strudel',
      'felixroos-1-lofi.strudel',
      'felixroos-2-pop.strudel',
      'fjpolo-1-lofi.strudel',
      'fjpolo-2-ambient.strudel',
      'fox-1-chiptune.strudel',
      'fox-2-pop.strudel',
      'free-drums-1-trap.strudel',
      'free-drums-2-boom_bap.strudel',
      'garden-1-ambient.strudel',
      'garden-2-lofi.strudel',
      'graffathon-1-chiptune.strudel',
      'graffathon-2-techno.strudel',
      'greg-drums-1-house.strudel',
      'greg-drums-2-techno.strudel',
      'juj-1-idm.strudel',
      'juj-2-trap.strudel',
      'k09-1-acid.strudel',
      'k09-2-house.strudel',
      'kaiye10-1-trap.strudel',
      'kaiye10-2-lofi.strudel',
      'mirus-1-ambient.strudel',
      'mirus-2-acid.strudel',
      'ms-teams-1-pop.strudel',
      'ms-teams-2-idm.strudel',
      'msl-1-lofi.strudel',
      'msl-2-house.strudel',
      'nikeryms-1-techno.strudel',
      'nikeryms-2-trap.strudel',
      'patch-hh-1-boom_bap.strudel',
      'patch-hh-2-trap.strudel',
      'patch-lofi-1-lofi.strudel',
      'patch-lofi-2-boom_bap.strudel',
      'patch-techno-1-techno.strudel',
      'patch-techno-2-acid.strudel',
      'polifonia-1-ambient.strudel',
      'polifonia-2-pop.strudel',
      'quantum-1-acid.strudel',
      'quantum-2-idm.strudel',
      'rikybac15-1-pop.strudel',
      'rikybac15-2-boom_bap.strudel',
      'rochormatic-1-idm.strudel',
      'rochormatic-2-ambient.strudel',
      'spicule-1-idm.strudel',
      'spicule-2-techno.strudel',
      'strudeldirt-1-boom_bap.strudel',
      'strudeldirt-2-dnb.strudel',
      'terrorhank-1-techno.strudel',
      'terrorhank-2-dnb.strudel',
      'tesspilot-1-trap.strudel',
      'tesspilot-2-house.strudel',
      'tidal-drums-1-techno.strudel',
      'tidal-drums-2-house.strudel',
      'todepond-1-idm.strudel',
      'todepond-2-ambient.strudel',
      'tr909-1-house.strudel',
      'tr909-2-techno.strudel',
      'vasily-1-lofi.strudel',
      'vasily-2-house.strudel',
      'vcsl-1-pop.strudel',
      'vcsl-2-ambient.strudel',
      'waveforms-1-acid.strudel',
      'waveforms-2-ambient.strudel',
      'wyan-1-pop.strudel',
      'wyan-2-house.strudel',
    ],
  },
];
