const PLAYLISTS = [
  {
    id: 'lofi',
    label: 'LOFI',
    path: '../lofi/',
    mode: 'player',
    files: [
      'song-01-3am-rain.strudel',
      'song-02-blue-smoke.strudel',
      'song-03-sunday-corner.strudel',
      'song-04-midnight-walk.strudel',
      'song-05-cafe-creme.strudel',
      'song-06-harbour-fog.strudel',
      'song-07-golden-afternoon.strudel',
      'song-08-neon-puddles.strudel',
      'song-09-midnight-thoughts.strudel',
      'song-10-lazy-afternoon.strudel',
      'song-11-rainy-window.strudel',
      'song-12-morning-stroll.strudel',
      'song-13-evening-reflections.strudel',
      'song-14-sunrise-hope.strudel',
      'song-15-night-whispers.strudel',
      'song-16-dark-dreams.strudel',
      'song-17-quiet-streets.strudel',
      'song-18-summer-breeze.strudel',
      'song-19-velvet-night.strudel',
      'song-20-coffee-shop-afternoon.strudel',
      'song-21-winter-silence.strudel',
      'song-22-ocean-drift.strudel',
      'song-23-urban-solitude.strudel',
      'song-24-starlight-garden.strudel',
      'song-25-autumn-leaves.strudel',
    ],
  },
  {
    id: 'rim',
    label: 'RIM',
    path: '../rim/',
    mode: 'player',
    files: [
      'song-01-dusty-trail.strudel',
      'song-02-campfire-lullaby.strudel',
      'song-03-prairie-wind.strudel',
      'song-04-old-tin-roof.strudel',
      'song-05-sagebrush-sunset.strudel',
      'song-06-lonesome-canyon.strudel',
      'song-07-creek-crossing.strudel',
      'song-08-red-mesa-morning.strudel',
      'song-09-old-porch-swing.strudel',
      'song-10-desert-stars.strudel',
    ],
  },
  {
    id: 'acid',
    label: 'ACID',
    path: '../acid/',
    mode: 'player',
    files: [
      'acid-01-storm-warning.strudel',
      'acid-02-trance-ascension.strudel',
      'acid-03-chrome-cathedral.strudel',
      'acid-04-neural-dissolve.strudel',
      'acid-05-rave-protocol.strudel',
    ],
  },
  {
    id: 'skola',
    label: 'SKOLA',
    path: '../Skola/',
    mode: 'code',
    files: [
      'lesson-01-rhythm-basics.strudel',
      'lesson-02-mini-notation.strudel',
      'lesson-03-notes-and-pitch.strudel',
      'lesson-04-scales-and-melody.strudel',
      'lesson-05-chords-and-harmony.strudel',
      'lesson-06-synths-and-sound-design.strudel',
      'lesson-07-effects.strudel',
      'lesson-08-advanced-rhythm.strudel',
      'lesson-09-structure-and-arrangement.strudel',
      'lesson-10-full-track.strudel',
      'cheat-01-rhythm-and-patterns.strudel',
      'cheat-02-pitch-and-harmony.strudel',
      'cheat-03-sound-and-effects.strudel',
      'cheat-04-advanced-modifiers.strudel',
      'cheat-05-advanced-effects.strudel',
      'example.strudel',
    ],
  },
  {
    id: 'techno',
    label: 'TECHNO',
    path: '../TehnoSkola/',
    mode: 'code',
    files: [
      'techno-01-detroit.strudel',
      'techno-02-berlin-minimal.strudel',
      'techno-03-acid-techno.strudel',
      'techno-04-dub-techno.strudel',
      'techno-05-industrial-techno.strudel',
      'techno-06-hard-techno.strudel',
      'techno-07-hypnotic-dark.strudel',
      'techno-08-melodic-techno.strudel',
      'techno-09-trance.strudel',
      'techno-10-gabber.strudel',
    ],
  },
];
